[package]
name = "kvd-net"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
thiserror = "2.0.16"
tokio = { version = "1.47.1", features = ["full"] }
tracing = "0.1.41"
kvd-core = { path = "../kvd-core" }
regex = "1.11.2"
